[package]
name = "massive-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
massive-geometry = { workspace = true }
massive-renderer = { workspace = true }
massive-shapes = { workspace = true }
winit = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
wgpu = { workspace = true }
anyhow = { workspace = true }
cosmic-text = { workspace = true }
cgmath = { workspace = true }

[dev-dependencies]
swash = { workspace = true }
bytemuck = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
derive_more = { workspace = true }
inlyne = { workspace = true }
