[workspace]
resolver = "2"

members = [
    "geometry",
    "shapes",
    "renderer",
    "shell",
    "inlyne",
]

exclude = [
    "rust-analyzer"
]

[workspace.metadata]
# For trunk
root-package = "shell"

# exclude = [ "inlyne" ]

[workspace.dependencies]
massive-geometry = { path = "geometry" }
massive-shell = { path = "shell" }
massive-renderer = { path = "renderer" }
massive-shapes = { path = "shapes" }
inlyne = { path = "inlyne" }

log = "0.4.19"
env_logger = "0.11.3"
serde_tuple = "0.5.0"
serde = { version = "1.0.164", features = ["derive"] }
derive_more = "0.99.17"
# rt-multi-thread is not supported on wasm.
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
wgpu = "0.19.4"
anyhow = "1.0.71"
swash = "0.1.8"
bytemuck = { version = "1.13.1", features = ["derive"] }
bitflags = { version = "2.3.3" }
cgmath = "0.18.0"
cosmic-text = { version = "0.11.2", features = ["swash"] }
winit = { version = "0.29.15", features = ["rwh_06"] }
approx = "0.5.1"
flo_curves = "0.7.2"
static_assertions = "1.1.0"
itertools = "0.12.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-flame = "0.2.0"
tracing-chrome = "0.7.2"

