[workspace]

resolver = "2"

members = [
    "geometry",
    "shapes",
    "renderer",
    "shell",
    "inlyne"
]

# exclude = [ "inlyne" ]

[workspace.dependencies]
massive-geometry = { path = "geometry" }
massive-shell = { path = "shell" }
massive-renderer = { path = "renderer" }
massive-shapes = { path = "shapes" }
inlyne = { path = "inlyne" }

log = "0.4.19"
env_logger = "0.11.3"
serde_tuple = "0.5.0"
serde = { version = "1.0.164", features = ["derive"] }
derive_more = "0.99.17"
# TODO: Only select the features we need
tokio = { version = "1.29.1", features = ["full"] }
wgpu = "0.19.3"
anyhow = "1.0.71"
swash = "0.1.8"
bytemuck = { version = "1.13.1", features = ["derive"] }
bitflags = { version = "2.3.3" }
cgmath = "0.18.0"
cosmic-text = { version = "0.11.2", features = ["swash"] }
winit = "0.29.14"
approx = "0.5.1"
flo_curves = "0.7.2"
