[package]
name = "massive-shapes"
version = "0.1.0"
edition = "2021"

[dependencies]
massive-geometry = { workspace = true }
# TODO: This is a bit heavyweight here, we need it for the CacheKey
cosmic-text = { workspace = true }
derive_more = { workspace = true }
cgmath = { workspace = true }