name: 'qa'
on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: 'Install toolchain'
      uses: dtolnay/rust-toolchain@stable

    - name: 'Test'
      run: cargo test --all-targets

  formatting:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: 'Install toolchain'
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: 'Check Formatting'
      run: | 
        cargo fmt -- --check
